version: '3'

# Containers
services:
  teams-maker-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: teams-maker-production-db
    ports:
      - 1434:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword123
    restart: always
    volumes:
      - sqldata:/var/opt/mssql/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssword123 -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  teams-maker-api:
    image: teams-maker-base
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teams-maker-api
    ports:
      - 7555:8080
      - 7556:443
    restart: always
    depends_on:
      - teams-maker-db
# Volumes
volumes:
  sqldata:
 
